// Package ambilight implements a MPD client that is able to play .mood files
// generated by the moodbar utility: https://en.wikipedia.org/wiki/Moodbar
// Those are files that consist of 1000 RGB triples of which each represents
// the composition of frequencies at a certain point in an audio file.
//
// In other words: An audio file is split in 1000(*) little parts where each
// part is colored based on the low frequencies (red), mids (green) and highs
// (blue). The combined color is then saved as RGB triple.
//
// This mpd client can automatically create a dir with a .mood database.
// When a song is played the respective .mood file is located and loaded
// and synchronized to the music. Additionally a bit of color correction
// is done and (linear) fading is done inbetween the individual samples
// for a smoother look.
//
// (*) Fixed number given by the moodbar, okay for most songs today,
//     not very suitable for e.g. Moonsorrow with their 30+ minute songs.
package ambilight
